---

- name: Install Packages (Ubuntu)
  apt:
    state: present
    name:
      - iptables-persistent
  when: ansible_distribution == "Ubuntu"

- name: Install Packages (CentOS)
  yum:
    state: present
    name:
      - iptables-services
  when: ansible_distribution == "CentOS"


- name: Remove Packages
  package:
    state: absent
    name:
      - ufw
      - firewalld

- name: Configure base firewall
  include_tasks: "{{ playbook_dir }}/lib/firewall-base.yml"

- name: Save Firewall Configuration
  include_tasks: "{{ playbook_dir}}/lib/firewall-save.yml"

- name: Enable services (Ubuntu)
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - netfilter-persistent
  when: ansible_distribution == "Ubuntu"

- name: Enable services (CentOS)
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - iptables
  when: ansible_distribution == "CentOS"

...