---

# Ensure we are running Ubuntu
- name: Ubuntu distribution check
  fail:
    msg: "Only ubuntu is supported for this role"
  when: ansible_distribution != 'Ubuntu'

- name: Storage configuration
  include_tasks: storage.yml

# Configure DNS resolution
- name: Resolver configuration
  include_tasks: "resolver.yml"

# Configure hostname
- name: System configuration
  include_tasks: "system.yml"

# Install packages
- name: Package configuration
  include_tasks: packages.yml

# Configure groups
- name: Configure groups
  include_tasks: groups.yml

# Configure user accounts
- name: Configure users
  include_tasks: users.yml

# Base Firewall configuration
- name: Firewall configuration
  include_tasks: firewall.yml

# Sudoers configuration
- name: Sudoers configuration
  include_tasks: sudoers.yml

# SSH Configuration
- name: sshd configuration
  include_tasks: sshd.yml

# VM Tools Configuration
- name: VM Tools configuration
  include_tasks: vmtools.yml

# NTP Configuration
- name: NTP Configuration
  include_tasks: ntpd.yml

# Utility configuration
- name: Utility configuration
  include_tasks: utility.yml
