---

- name: Apt proxy configuration
  template:
    src: apt_proxy.j2
    dest: /etc/apt/apt.conf.d/80-proxy.conf
    owner: root
    group: root
    mode: 0644

- name: Gather service information
  ansible.builtin.service_facts:

- name: Unattended Upgrade Service
  service:
    name: unattended-upgrades
    state: "{{ 'started' if unattended_upgrade_service_enable else 'stopped' }}"
    enabled: "{{ unattended_upgrade_service_enable }}"
  when: "'unattended-upgrades.service' in ansible_facts.services"

- name: Unattended Upgrade Config
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: true
    owner: root
    group: root
    mode: "0644"
  loop:
    - regexp: >-
        ^APT::Periodic::Unattended-Upgrade.*
      line: >-
        APT::Periodic::Unattended-Upgrade "{{ '1' if unattended_upgrade_service_enable else '0' }}";
    - regexp: >-
        ^APT::Periodic::Update-Package-Lists.*
      line: >-
        APT::Periodic::Update-Package-Lists "{{ '1' if unattended_upgrade_service_enable else '0' }}";

- name: Daily APT Upgrade
  service:
    name: apt-daily-upgrade.timer
    state: "{{ 'started' if apt_daily_upgrade_enable else 'stopped' }}"
    enabled: "{{ apt_daily_upgrade_enable }}"

- name: Update Apt cache
  apt:
    update_cache: yes
  ignore_errors: true
  changed_when: false

- name: Install Packages
  apt:
    state: present
    name:
      - software-properties-common
      - python3
      - apt-transport-https
      - ca-certificates
      - parted
      - sudo

# Remove packages
- name: Remove Packages
  package:
    state: absent
    name:
      - cloud-init
