---

- name: Apt proxy configuration
  template:
    src: apt_proxy.j2
    dest: /etc/apt/apt.conf.d/80-proxy.conf
    owner: root
    group: root
    mode: 0644

- name: Unattended Upgrade Service
  service:
    name: unattended-upgrades
    state: "{{ 'running' if unattended_upgrade_service_enable else 'stopped' }}"
    enabled: "{{ unattended_upgrade_service_enable }}"

- name: Daily APT Upgrade
  service:
    name: apt-daily-upgrade.timer
    state: "{{ 'running' if apt_daily_upgrade_enable else 'stopped' }}"
    enabled: "{{ apt_daily_upgrade_enable }}"

- name: Update Apt cache
  apt:
    update_cache: yes
  ignore_errors: true
  changed_when: false

- name: Install Packages
  apt:
    state: present
    name:
      - software-properties-common
      - python3
      - apt-transport-https
      - ca-certificates
      - parted
      - sudo
      - zfsutils-linux

# Remove packages
- name: Remove Packages
  package:
    state: absent
    name:
      - cloud-init
