---

- name: resolve.temp permissions
  file:
    path: /etc/resolv.conf.temp
    owner: root
    group: root
    mode: 0644
    state: touch

- name: Save resolv.conf
  shell: "cat /etc/resolv.conf > /etc/resolv.conf.temp"

- name: Remove resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: Replace resolv.conf
  command: mv /etc/resolv.conf.temp /etc/resolv.conf

...