---

- name: Install Packages
  apt:
    state: present
    name:
      - sshpass
      - openssh-server
      - openssh-sftp-server

# Password authentication
- name: SSH Config Patching
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ ssh_config_patch.regexp }}"
    line: "{{ ssh_config_patch.line }}"
    state: present
  register: config
  loop_control:
    loop_var: ssh_config_patch
  loop:
    - regexp: "^PasswordAuthentication "
      line: "PasswordAuthentication yes"
    - regexp: "^PermitRootLogin "
      line: "PermitRootLogin no"
    - regexp: "^AllowGroups "
      line: "AllowGroups remotessh"

# SSH service state
- name: SSH Server Enabled
  service:
    name: ssh
    enabled: yes
    state: "{{ 'restarted' if config.changed else 'started' }}"
