---

- name: SSHD default state
  set_fact:
    ssh_service_state: "started"

- name: sshd config file
  file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: Determine operational ssh port
  set_fact:
    operational_ansible_ssh_port: "{{ desired_ansible_ssh_port | default(22) }}"

##
# Port configuration
- name: SSH Port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Port "
    line: "Port {{ operational_ansible_ssh_port }}"
    state: present
  register: config

- name: Trigger restart
  set_fact:
    ssh_service_state: "restarted"
  when: config.changed

##
# Allowed Groups
- name: SSH AllowGroups
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AllowGroups "
    line: "AllowGroups remotessh"
    state: present
  register: config

- name: Trigger restart
  set_fact:
    ssh_service_state: "restarted"
  when: config.changed

##
# Disable remote root login
- name: SSH PermitRootLogin
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin "
    line: "PermitRootLogin no"
    state: present
  register: config

- name: Trigger restart
  set_fact:
    ssh_service_state: "restarted"
  when: config.changed

##
# Password authentication
- name: SSH PasswordAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication "
    line: "PasswordAuthentication yes"
    state: present
  register: config

- name: Trigger restart
  set_fact:
    ssh_service_state: "restarted"
  when: config.changed

- name: SSH Server Enabled
  service:
    name: sshd
    enabled: yes
    state: "{{ ssh_service_state }}"

- name: Set ssh port to what was configured
  set_fact:
    ansible_ssh_port: "{{ operational_ansible_ssh_port }}"

...