---

- name: nopassword sudoers group
  group:
    name: npwsudo
    state: present

- name: Configure nopassword sudoers file
  copy:
    content: |
      %npwsudo ALL=(ALL:ALL) NOPASSWD:ALL
    dest: /etc/sudoers.d/npwsudo
    owner: root
    group: root
    mode: "0640"

- name: sudoers include directory
  file:
    state: directory
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755

- name: /etc/sudoers include
  lineinfile:
    path: /etc/sudoers
    regexp: "^#includedir /etc/sudoers.d$"
    line: "#includedir /etc/sudoers.d"
    state: present
